### ISSUE TITLE
image text Retriver

### ISSUE THREAD

**Issue by Guardian-in-the-WF** [marshuang80/gloria#13]
Great work. Could you please supply an example about how to use the class Retriver? Thanks.

**Comment by marshuang80** [comment]
Hi @Guardian-in-the-WF, thank you for the interest in our work! The retriever is exactly the same as our zero-shot learning modules:
 
https://github.com/marshuang80/gloria/blob/416466af1036294301a872e4da169fefc137a192/gloria/gloria.py#L240

But instead of passing in cls_txt_mapping, you'l pass in the retrieving target. 

Hope this helps!
